# Site settings
title: Portfólio de Análise de Dados I
email: marcosnascimennto@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Serão disponibilizados aqui vários posts desenvolvidos durante o curso de
  Análise de Dados I da Universidade Federal de Campina Grande (UFCG). Dentre
  os posts você poderá ver várias técnicas de análise explolatória e descritiva
  de dados, técnicas de visualização, agrupamento e etc sem falar dos conjuntos
  de dados que remetem a séries, atores de Hollywood etre outros.
baseurl: "/knitr-jekyll-ad1" # the base hostname & protocol for your site
url: "https://marcosasn.github.io/knitr-jekyll-ad1/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  marcosasn
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
