# Site settings
title: Análise de Dados I
email: marcosnascimennto@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/knitr-jekyll-ad1" # the base hostname & protocol for your site
url: "https://marcosasn.github.io/knitr-jekyll-ad1/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  marcosasn
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
